services:
  # Бэкенд (API)
  - type: web
    name: crypto-analyzer-api
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://crypto-analyzer-client.onrender.com/auth-callback
      - key: CRYPTO_LIST
        value: BTC,ETH,XRP,BNB,SOL,DOGE,ADA,TRX,TON,AVAX,MATIC,LINK,SHIB,LTC,DOT,BCH,ICP,UNI,ATOM,XLM,HBAR,NEAR,APT,VET,FIL,OP,ARB,ALGO,AAVE,GRT,IMX,RNDR,FLOW,SUI,TIA,MKR,LDO,QNT,AXS,RUNE,GALA,STX,FTM,EOS,THETA,CRO,HNT,PEPE,BONK,WIF

  # Фронтенд (Клиент)
  - type: web
    name: crypto-analyzer-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://crypto-analyzer-api.onrender.com/api